// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jeqlvlvgfexxhmpekwtq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplcWx2bHZnZmV4eGhtcGVrd3RxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMDgyMDQsImV4cCI6MjA2OTc4NDIwNH0.M73x-5GRC18N0bcZmnA3V4Vh2HU38Q2R6uyFUG9llHY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});